# Welcome to Numpy

In [1]:
# Numpy is a python library used a numerical computing.

In [1]:
import numpy as np

In [3]:
myarr=np.array([[3,6,32,7]],np.int64)

In [4]:
myarr[0,1]

np.int64(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=67

In [8]:
myarr

array([[ 3, 67, 32,  7]])

# Array creation : Conversion From Other Python Structures

In [9]:
listarray=np.array([[1,2,3],[5,8,7],[3,4,5]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 7],
       [3, 4, 5]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
linspace=np.linspace(1,50,10)

In [19]:
linspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp=np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.45701377e-308, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 7.56601165e-307],
       [1.69118787e-306, 9.34609790e-307, 1.33511562e-306,
        6.89805151e-307, 7.56592338e-307, 6.89807188e-307],
       [1.69118787e-306, 1.78021391e-306, 8.34451504e-308,
        1.78022342e-306, 8.06635958e-308, 8.34424342e-308]])

In [22]:
emp_like=np.empty_like(linspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide=np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr=np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr=arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr=arr.ravel()

In [32]:
arr.shape

(99,)

In [33]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [34]:
ar=np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar.sum(axis=0)

array([12,  8,  9])

In [37]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
arr.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0

In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.nbytes

72

In [44]:
one =np.array([1,3,4,654,2])

In [45]:
one.argmax()

np.int64(3)

In [46]:
one.argmin()

np.int64(0)

In [47]:
one.argsort()

array([0, 4, 1, 2, 3])

In [48]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [49]:
ar.argmin()

np.int64(8)

In [50]:
ar.argmax()

np.int64(6)

In [51]:
ar.argmax(axis=0)

array([2, 1, 1])

In [52]:
ar.argmax(axis=1)

array([2, 2, 0])

In [53]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

# NUMPY

In [54]:
#Library : computation

In [55]:
import numpy as np

In [56]:
#List : array: most adavanced list

In [57]:
my_list=[1,2,3]

In [58]:
my_list

[1, 2, 3]

In [59]:
np.array(my_list)

array([1, 2, 3])

In [61]:
array=np.array(my_list)

In [62]:
array

array([1, 2, 3])

In [63]:
type(array)

numpy.ndarray

In [64]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
array=np.array(my_matrix)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [65]:
# list comprehension :defining methods in short
l=[i for i in range(0,10)]

In [66]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
arr=np.arange(0,10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#zeroes ,ones
np.zeros(3)

array([0., 0., 0.])

In [70]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
# linspace: linear space :
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [75]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [76]:
# eye 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
# random

In [78]:
np.random.rand(2)

array([0.13085423, 0.67642361])

In [79]:
np.random.rand(5,5)

array([[0.49968329, 0.12128907, 0.49074301, 0.0687328 , 0.58380022],
       [0.24503841, 0.78371565, 0.84661607, 0.09705982, 0.57473815],
       [0.41887473, 0.35259158, 0.81530219, 0.92525563, 0.42823748],
       [0.20047309, 0.83359471, 0.73246613, 0.07408217, 0.880067  ],
       [0.70598237, 0.74349097, 0.45538525, 0.55887139, 0.70182031]])

In [81]:
# np.random.randn() : negative number proximity
np.random.randn(2)

array([ 0.04013692, -1.3461521 ])

In [82]:
np.random.randn(5,5)

array([[ 1.47474554,  0.82254609,  0.54188558,  1.33732271, -1.26957365],
       [-0.80381152, -0.78420522, -0.64769528,  0.81514699, -0.89336111],
       [-1.84109827, -0.11048919,  0.1031767 ,  0.672371  ,  1.00123399],
       [-0.20556995, -1.2507714 , -0.33178414,  0.61059095, -0.10528492],
       [ 0.18597587,  1.61999907, -1.33976672, -0.12247184,  0.96331503]])

In [85]:
#randint
np.random.randint(1,100,12)

array([13, 45, 34, 82,  5, 80, 81, 99, 38,  2, 93, 81], dtype=int32)

In [86]:
np.random.randint(1,100)

2

In [87]:
#seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [88]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [89]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [91]:
np.random.seed(41)
np.random.rand(5)

array([0.25092362, 0.04609582, 0.67681624, 0.04346949, 0.1164237 ])

In [95]:
# matrix : random number :0,50,10

In [8]:
arr=np.arange(25)
rarr=np.random.randint(0,50,10)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [98]:
rarr

array([26, 45, 44,  3, 35,  6, 48, 20, 22, 41], dtype=int32)

In [99]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
rarr.reshape(2,5) # first : rows ,second :column

array([[26, 45, 44,  3, 35],
       [ 6, 48, 20, 22, 41]], dtype=int32)

In [101]:
rarr.reshape(5,2)

array([[26, 45],
       [44,  3],
       [35,  6],
       [48, 20],
       [22, 41]], dtype=int32)

In [9]:
# min, max ,argmin
np.max(rarr)

np.int32(45)

In [10]:
rarr.min()

np.int32(12)

In [105]:
rarr.argmin()

np.int64(3)

In [106]:
rarr.argmax()

np.int64(6)

In [107]:
rarr

array([26, 45, 44,  3, 35,  6, 48, 20, 22, 41], dtype=int32)

In [108]:
#shape of array
arr.shape

(25,)

In [109]:
arr.reshape(5,5).shape

(5, 5)

In [113]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [115]:
arr[1]

np.int64(1)

In [116]:
# indexing and slacing 
arr2=np.arange(20,40)

In [117]:
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [118]:
arr2[5]

np.int64(25)

In [120]:
arr2[0:4]

array([20, 21, 22, 23])

In [121]:
arr2[1:7:2]

array([21, 23, 25])

In [123]:
arr2[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20])

In [124]:
# Broadcasting
arr3=np.arange(0,10)

In [125]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
slice_arr=arr3[0:5]

In [139]:
slice_arr

array([0, 1, 2, 3, 4])

In [140]:
slice_arr[0]=99

In [141]:
slice_arr

array([99,  1,  2,  3,  4])

In [142]:
slice_arr[:]=99

In [143]:
slice_arr

array([99, 99, 99, 99, 99])

In [144]:
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [145]:
arr_copy=arr3.copy()

In [146]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [147]:
slice_copy=arr_copy[0:5]

In [148]:
slice_copy

array([99, 99, 99, 99, 99])

In [149]:
slice_copy[:]=66

In [150]:
slice_copy

array([66, 66, 66, 66, 66])

In [151]:
arr_copy

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9])

In [6]:
#self work 
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]

In [17]:
a=np.array([1,2,3,4])

In [18]:
np.max(a)

np.int64(4)

In [19]:
a.max()

np.int64(4)

In [20]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [21]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [22]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [23]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
np.sum(a)

np.int64(10)

In [25]:
np.mean(a)

np.float64(2.5)

In [26]:
np.median(a)

np.float64(2.5)

In [27]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)

[[ 6  8]
 [10 12]]

In [28]:
print(A@B)

[[19 22]
 [43 50]]

In [29]:
print(np.dot(A,B))

[[19 22]
 [43 50]]

In [30]:
A.T

array([[1, 3],
       [2, 4]])

In [31]:
print(np.linalg.det(A))

-2.0000000000000004

In [32]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]

# Numpy broadcasting

In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[2][0]

np.int64(7)

In [5]:
arr[2][2]

np.int64(9)

In [8]:
# 2d array slincing

In [14]:
arr[:2,1:] # 0th rows starts ,end 2nd rows and 1st column start ,end last column # by default start with 0

array([[2, 3],
       [5, 6]])

In [13]:
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [15]:
# conditional statements
arr=np.arange(1,11)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [18]:
arr<=3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [19]:
arr==4

array([False, False, False,  True, False, False, False, False, False,
       False])

In [20]:
arr!=5

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [21]:
bool_arr=arr>4

In [22]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr[arr!=5]

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

In [2]:
np.random.rand(5)

array([0.29207023, 0.21777791, 0.41728166, 0.14604561, 0.19487084])

In [5]:
np.random.randn(2,3)

array([[ 0.23766457,  1.35325963, -0.50096955],
       [-0.59331845,  0.93258608, -0.24927214]])

In [6]:
np.random.choice([2,3,45,8])

np.int64(45)

In [9]:
np.random.seed(0)
np.random.rand(1)

array([0.5488135])

In [10]:
np.random.seed(0)
np.random.rand(1)

array([0.5488135])

# Numpy Operations

In [25]:
l=[1,2,3]
l2=[4,5,6]
l3=l+l2
print(l3)

[1, 2, 3, 4, 5, 6]

In [26]:
arr=np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr+arr #addition

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr2=np.arange(11,15)
arr2

array([11, 12, 13, 14])

In [31]:
arr+arr2

ValueError: operands could not be broadcast together with shapes (10,) (4,)

In [32]:
arr*arr # multiplication

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [33]:
arr-arr # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
arr/arr #division

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arr*4 # also multiply by specific number

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [37]:
# numpy : mathmatical computation

In [38]:
# more math 
arr2=arr**2
arr2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [39]:
np.sqrt(arr2)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
# exponent :1.0000E+2: scientific :

In [42]:
np.exp(arr2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [45]:
#sin ,cosec ,tan ,cosec ,cot,sec,log

In [44]:
np.sin(arr2)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [46]:
np.cos(arr2)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [47]:
np.tan(arr2)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224, -0.13352641,
        7.75047091, -3.17290855,  2.34786031, -0.81099442, -0.58721392])

In [48]:
np.log(arr2)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [51]:
np.cosec(arr2)

AttributeError: module 'numpy' has no attribute 'cosec'

In [52]:
# statisticls funtion in numpy: sum ,max,mean,min
np.sum(arr2)

np.int64(385)

In [53]:
np.mean(arr2)

np.float64(38.5)

In [54]:
np.max(arr2)

np.int64(100)

In [55]:
np.min(arr2)

np.int64(1)

In [56]:
a2=np.array([[1,2,3],[5,6,7],[3,7,8]])
np.sum(a2)

np.int64(42)

In [58]:
a2.sum(axis=0) # axis =0 : rows ,axis=1:column

array([ 9, 15, 18])

In [59]:
a2.sum(axis=1)

array([ 6, 18, 18])

In [61]:
a2.shape

(3, 3)

# Pandas

In [2]:
import pandas as pd

# Index and data lists

In [64]:
# we can create a Series Python lists(also from Numpy arrays)

In [65]:
myindex=['USA','Canada','Maxico']

In [66]:
mydata=[1776,1867,1821]

In [68]:
myser=pd.Series(data=mydata)

In [69]:
myser

0    1776
1    1867
2    1821
dtype: int64

In [70]:
pd.Series(data=mydata,index=myindex)

USA       1776
Canada    1867
Maxico    1821
dtype: int64

In [79]:
ran_data=np.random.randint(0,100,4)

In [80]:
ran_data

array([ 3, 69, 47, 65], dtype=int32)

In [82]:
names=['Andrew','Bobo','Claire','David']

In [83]:
ages=pd.Series(ran_data,names)

In [84]:
ages

Andrew     3
Bobo      69
Claire    47
David     65
dtype: int32

In [85]:
# From a Dictionary

In [87]:
ages={'Samay':5,'Frank':10,'Spike':7}
ages

{'Samay': 5, 'Frank': 10, 'Spike': 7}

In [88]:
pd.Series(ages)

Samay     5
Frank    10
Spike     7
dtype: int64

In [89]:
#Task:
# Employee expenses  are being stored in an pandas series called expenses.what are Bob's expenses?

In [4]:
expenses=[10002,8000,3000,5000]

In [6]:
Employee=['Aniket','Bob','charlei','Viart']
final=pd.Series(expenses,Employee)
final

Aniket     10002
Bob         8000
charlei     3000
Viart       5000
dtype: int64

In [7]:
final['Bob']

np.int64(8000)

In [101]:
# or

In [102]:
expenses=pd.Series({'Aniket':20,'Bob':50,'Virat':90})
bob=expenses['Bob']

In [103]:
bob

np.int64(50)

In [9]:
#Imaginary Sales Data for 1st and 2nd Quarters for Global Commpany
q1={'japan':80,'China':450,'India':200,'USA':250}
q2={'Brazil':100,'China':500,'India':200,'USA':250}

In [10]:
# convert into pandas Series
sales_Q1=pd.Series(q1)
sales_Q2=pd.Series(q2)

In [11]:
sales_Q1

japan     80
China    450
India    200
USA      250
dtype: int64

In [12]:
#call values based on Named index
sales_Q1['japan']

np.int64(80)

In [13]:
# integes Based Locations Information also retained!
sales_Q1[0]

C:\Users\3511\AppData\Local\Temp\ipykernel_15792\1714265844.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_Q1[0]

np.int64(80)

# Dataframes

** Datframes are an extremely Powerful tool and a extention of the Pandas Series By definition all a DataFrame is: **

** A Pandas DataFrame consists of multiple Pandas Series that share index values.**

# Import

In [2]:
import numpy as np
import pandas as pd

# Creating a DataFrames

In [4]:
# help(pd.DataFrames)

In [17]:
# From dictionary
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df

   A  B
0  1  4
1  2  5
2  3  6

In [20]:
# From list of list
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['X','Y','Z'])
df

   X  Y  Z
0  1  2  3
1  4  5  6

In [21]:
# Creating from Python objects
# Make sure the seed is in the same cell as the random call
np.random.seed(101)
mydata=np.random.randint(0,101,(4,3))

In [22]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [23]:
df=pd.DataFrame(np.arange(9).reshape(3,3),columns=['A','B','C'])
df

   A  B  C
0  0  1  2
1  3  4  5
2  6  7  8

In [7]:
myindex=['CA','NY','AZ','TX']

In [8]:
mycolumn=['jan','feb','Mar']

In [24]:
df=pd.DataFrame(mydata,['CA','NY','AZ','TX'],['jan','feb','Mar'])
df

    jan  feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [17]:
df=pd.DataFrame(data=mydata,index=myindex)

In [18]:
df

     0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63

In [22]:
df=pd.DataFrame(data=mydata,index=myindex,columns=mycolumn)

In [23]:
df

    jan  feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [30]:
name=['Aniket','Virat','Rohit','Vikash']

In [28]:
subject=['Math','Computer','Science']

In [31]:
df=pd.DataFrame(data=mydata,index=name,columns=subject)

In [32]:
df

        Math  Computer  Science
Aniket    95        11       81
Virat     70        63       87
Rohit     75         9       77
Vikash    40         4       63

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Aniket to Vikash
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Math      4 non-null      int32
 1   Computer  4 non-null      int32
 2   Science   4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

# Print your current directory file path with pwd

In [35]:
pwd

'C:\\Users\\3511\\Desktop\\AniketPython'

# List the files in your corrent directory with ls

In [37]:
ls

 Volume in drive C is OS
 Volume Serial Number is 8650-8780

 Directory of C:\Users\3511\Desktop\AniketPython

13-10-2025  18:16    <DIR>          .
02-10-2025  12:51    <DIR>          ..
12-10-2025  17:05    <DIR>          .ipynb_checkpoints
24-09-2025  18:40    <DIR>          __pycache__
10-10-2025  23:14            23,938 00-NumPy-Arrays.ipynb
10-10-2025  23:12            12,315 01-NumPy-Indexing-and-Selection.ipynb
10-10-2025  23:14            11,408 02-NumPy-Operations.ipynb
10-10-2025  23:11            22,823 03-NumPy-Exercises.ipynb
19-09-2025  19:25            94,503 Demo.ipynb
13-10-2025  18:14             5,022 example.xlsx
29-09-2025  01:03            17,984 Fun.ipynb
01-10-2025  18:00            38,311 Fun2.ipynb
26-09-2025  22:16            21,543 HW.ipynb
13-10-2025  18:14               177 movie_scores.csv
13-10-2025  18:14            17,727 mpg.csv
13-10-2025  18:14             5,022 my_excel_file.xlsx
24-09-2025  18:36                81 Mymodule.py
13-10-2025  18:14                51 new_file.csv
13-10-2025  18:14             5,021 new_workbook.xlsx
13-10-2025  18:16           100,753 Numpy.ipynb
11-10-2025  22:30            24,039 NumpyQuestionsheet.ipynb
06-10-2025  18:35            18,075 OOPS.ipynb
12-10-2025  18:49             7,687 Pandas.ipynb
13-10-2025  18:14             5,459 RetailSales_BeerWineLiquor.csv
13-10-2025  18:14             1,320 Sales_Funnel_CRM.csv
13-10-2025  18:14            18,752 tips.csv
              22 File(s)        452,011 bytes
               4 Dir(s)  340,662,824,960 bytes free

In [3]:
df=pd.read_csv('tips.csv')

In [4]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# Obtaining Basic Information About DataFrames

In [43]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [44]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [45]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

In [46]:
df.tail(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [47]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [48]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

# Selection and Indexing

# COLUMNS

In [32]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# Grab  a single Column

In [49]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [33]:
type(df['total_bill'])

pandas.core.series.Series

# Grab multiple column

In [16]:
#Note how its a python list of column names! Thus the double brakets.
df[['total_bill','tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [34]:
type(df[['total_bill','tip']])

pandas.core.frame.DataFrame

# create New Columns

In [31]:
df['tip_percentage']=100*df['tip']/df['total_bill']

In [32]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,Sun2251,14.680765

In [20]:
df['price_per_person']=df['total_bill']/df['size']

** If you give any coloumn name which is already present it will not create new coloumn but will overwrite same coloumn **

In [21]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,Sun2251,14.680765

In [58]:
help(np.round)

Help on _ArrayFunctionDispatcher in module numpy:

round(a, decimals=0, out=None)
    Evenly round to the given number of decimals.

    Parameters
    ----------
    a : array_like
        Input data.
    decimals : int, optional
        Number of decimal places to round to (default: 0).  If
        decimals is negative, it specifies the number of positions to
        the left of the decimal point.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have
        the same shape as the expected output, but the type of the output
        values will be cast if necessary. See :ref:`ufuncs-output-type`
        for more details.

    Returns
    -------
    rounded_array : ndarray
        An array of the same type as `a`, containing the rounded values.
        Unless `out` was specified, a new array is created.  A reference to
        the result is returned.

        The real and imaginary parts of complex numbers are rounded
        separately.  The result of rounding a float is a float.

    See Also
    --------
    ndarray.round : equivalent method
    around : an alias for this function
    ceil, fix, floor, rint, trunc


    Notes
    -----
    For values exactly halfway between rounded decimal values, NumPy
    rounds to the nearest even value. Thus 1.5 and 2.5 round to 2.0,
    -0.5 and 0.5 round to 0.0, etc.

    ``np.round`` uses a fast but sometimes inexact algorithm to round
    floating-point datatypes. For positive `decimals` it is equivalent to
    ``np.true_divide(np.rint(a * 10**decimals), 10**decimals)``, which has
    error due to the inexact representation of decimal fractions in the IEEE
    floating point standard [1]_ and errors introduced when scaling by powers
    of ten. For instance, note the extra "1" in the following:

        >>> np.round(56294995342131.5, 3)
        56294995342131.51

    If your goal is to print such values with a fixed number of decimals, it is
    preferable to use numpy's float printing routines to limit the number of
    printed decimals:

        >>> np.format_float_positional(56294995342131.5, precision=3)
        '56294995342131.5'

    The float printing routines use an accurate but much more computationally
    demanding algorithm to compute the number of digits after the decimal
    point.

    Alternatively, Python's builtin `round` function uses a more accurate
    but slower algorithm for 64-bit floating point values:

        >>> round(56294995342131.5, 3)
        56294995342131.5
        >>> np.round(16.055, 2), round(16.055, 2)  # equals 16.0549999999999997
        (16.06, 16.05)


    References
    ----------
    .. [1] "Lecture Notes on the Status of IEEE 754", William Kahan,
           https://people.eecs.berkeley.edu/~wkahan/ieee754status/IEEE754.PDF

    Examples
    --------
    >>> import numpy as np
    >>> np.round([0.37, 1.64])
    array([0., 2.])
    >>> np.round([0.37, 1.64], decimals=1)
    array([0.4, 1.6])
    >>> np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
    array([0., 2., 2., 4., 4.])
    >>> np.round([1,2,3,11], decimals=1) # ndarray of ints is returned
    array([ 1,  2,  3, 11])
    >>> np.round([1,2,3,11], decimals=-1)
    array([ 0,  0,  0, 10])

# Adjust Existing Coloumns

In [33]:
#Because pandas is based on numpy,we get awesome capabilities with numpy's universal function
df['price_per_person']=np.round(df['price_per_person'],2)

In [48]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

# Removes columns

In [64]:
# df .drop('tip_percentages',axis=1)

In [36]:
df=df.drop('tip_percentage',axis=1)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# index Basic

In [66]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [53]:
df=df.reset_index()
df.head()

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [5]:
df=df.set_index('Payment ID')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [56]:
df=df.reset_index()

In [57]:
df.head()

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

# Grab a single Row

In [72]:
# Integer Based
df.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Payment ID                     Sun2959
Name: 0, dtype: object

In [60]:
#Name based
df.loc['Sun2959']

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [35]:
df=pd.DataFrame(np.arange(9).reshape(3,3),index=['A','B','C'],columns=['Man','Womwn','None'])
df

   Man  Womwn  None
A    0      1     2
B    3      4     5
C    6      7     8

In [36]:
df.iloc[0]

Man      0
Womwn    1
None     2
Name: A, dtype: int64

In [39]:
df.loc['C']

Man      6
Womwn    7
None     8
Name: C, dtype: int64

In [49]:
# self work
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
#df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])
df

   A  B
0  1  4
1  2  5
2  3  6

In [18]:
df['C']=df['A']*df['B']

In [19]:
df

   A  B   C
0  1  4   4
1  2  5  10
2  3  6  18

In [20]:
df.loc[3]=[10,11,12]

In [21]:
df

    A   B   C
0   1   4   4
1   2   5  10
2   3   6  18
3  10  11  12

In [22]:
df.drop('B',axis=1,inplace=True)

In [23]:
df

    A   C
0   1   4
1   2  10
2   3  18
3  10  12

In [24]:
df.drop(2,axis=0)

    A   C
0   1   4
1   2  10
3  10  12

In [25]:
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])

In [26]:
df

   A  B  C
0  1  2  3
1  4  5  6

In [29]:
#subset of rows and columns
df.loc[0:2,['A','B']]

   A  B
0  1  2
1  4  5

In [31]:
df.iloc[0:2,0:2]

   A  B
0  1  2
1  4  5

In [61]:
# conditional selection
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])
#df[df['A']>2]
df

   A  B  C
0  1  2  3
1  4  5  6

In [40]:
df[(df['A']>2) & (df['B']<6)]

   A  B  C
1  4  5  6

In [62]:
# indexing and renaming
df.set_index('A',inplace=True)
df

   B  C
A
1  2  3
4  5  6

In [63]:
df.reset_index(inplace=True)

In [64]:
df

   A  B  C
0  1  2  3
1  4  5  6

In [66]:
df.rename(columns={'A':'X'},inplace=True)

In [67]:
df

   X  B  C
0  1  2  3
1  4  5  6

# Remove Row

In [6]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [7]:
df.drop('Sun2959',axis=0).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882