In [1]:
import numpy as np
import pandas as pd

In [36]:
df=pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [9]:
#apply methods /function # not completed
def last_num(num):
    return str(num[-4:])

In [4]:
df['CC Number'][0]

np.int64(3560325168603410)

In [10]:
last_num('Sun2959')

'2959'

In [11]:
df['last Four']=df['Payment ID'].apply(last_num)

In [12]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,at17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,r672

In [13]:
# Create a function called quality which will check quality of the tip if tip is greater than 25% of bill quality is good otherwise bad.

In [17]:
def quality(tip,total_bill):
    if tip/total_bill>0.25:
        return "Generous"
    else:
        return "Other"

In [30]:
#apply :pandas
#Numpy: vectorise
# df['tip quality']=df[['total_bill','tip']].apply(Function name)# this is Pandas function.
df['tip_quality']=np.vectorize(quality)(df['total_bill'],df['tip'])# faster than 'apply' ,time complecity is less and this is Numpy function .

In [31]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4608,Generous,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,4458,Generous,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5260,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251,Generous,Generous

In [32]:
df['tip_quality2']=df[['tip','total_bill']].apply(lambda df :quality(df['total_bill'],df['tip']),axis=1)

In [33]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4608,Generous,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,4458,Generous,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5260,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251,Generous,Generous

In [35]:
# sort_value
df.sort_values(['tip','tip_quality'])# for multiple columns use ([1st,2nd,......])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,3455,Generous,Generous
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,3780,Generous,Generous
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,4801,Generous,Generous
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,5032,Generous,Generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,1025,Generous,Generous
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,8139,Generous,Generous
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,t239,Generous,Generous
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,4590,Generous,Generous
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,1954,Generous,Generous

In [38]:
df.sort_values('tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,3780,Generous,Generous
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,4801,Generous,Generous
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,3455,Generous,Generous
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,5032,Generous,Generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,1025,Generous,Generous
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,8139,Generous,Generous
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,t239,Generous,Generous
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,4590,Generous,Generous
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,1954,Generous,Generous

In [39]:
#corr
df[['total_bill','tip']].corr()

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [37]:
# values_counts
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [43]:
#replace
df['tip_quality']=df['tip_quality'].replace(to_replace='Other',value='poor')

In [44]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4608,Generous,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,4458,Generous,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5260,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251,Generous,Generous

In [45]:
#unique

In [47]:
df['size'].unique()

array([2, 3, 4, 1, 6, 5])

In [48]:
#duplicated(),drop_dulicates()
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [51]:
df.drop_duplicates()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4608,Generous,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,4458,Generous,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5260,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251,Generous,Generous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2657,Generous,Generous
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,1766,Generous,Generous
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,3880,Generous,Generous
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,at17,Generous,Generous
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,r672,Generous,Generous

In [56]:
sdf=pd.DataFrame([1,2,2],['a','b','c'])

In [57]:
sdf

   0
a  1
b  2
c  2

In [58]:
sdf.duplicated()

a    False
b    False
c     True
dtype: bool

In [59]:
sdf.drop_duplicates()

   0
a  1
b  2

In [62]:
# Between 
df['total_bill'].between(10,20,inclusive='both')# 'netheir' ,'left','right'

0       True
1       True
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool

In [65]:
# sample
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179,6179,Generous,Generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
79,17.29,2.71,Male,No,Thur,Lunch,2,8.64,Brian Diaz,4759290988169738,Thur9501,9501,Generous,Generous
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,213113680829581,Thur1446,1446,Generous,Generous
20,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4403296224639756,Sat1709,1709,Generous,Generous

In [66]:
df.sample(frac=0.10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735,6735,Generous,Generous
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679,9679,Generous,Generous
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987,9987,Generous,Generous
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4258682154026,Sat7872,7872,Generous,Generous
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628,9628,Generous,Generous
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5448125351489749,Sat9618,9618,Generous,Generous
117,10.65,1.50,Female,No,Thur,Lunch,2,5.32,Linda Zhang,3560509622598239,Thur9593,9593,Generous,Generous
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,213158685144262,Sun7015,7015,Generous,Generous
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,3880,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,2251,Generous,Generous
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,t239,Generous,Generous
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4317015327600068,Thur967,r967,Generous,Generous
194,16.58,4.00,Male,Yes,Thur,Lunch,2,8.29,Benjamin Weber,676210011505,Thur9318,9318,Generous,Generous
168,10.59,1.61,Female,Yes,Sat,Dinner,2,5.30,Sara Jimenez,502053147208,Sat9795,9795,Generous,Generous
123,15.95,2.00,Male,No,Thur,Lunch,2,7.98,Christopher Lang,4820629318698319,Thur1992,1992,Generous,Generous
86,13.03,2.00,Male,No,Thur,Lunch,2,6.52,Derek Thomas,213161022097557,Thur6793,6793,Generous,Generous
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,213109508670736,Fri4607,4607,Generous,Generous
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313,9313,Generous,Generous
30,9.55,1.45,Male,No,Sat,Dinner,2,4.78,Grant Hall,30196517521548,Sat4099,4099,Generous,Generous
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,5032,Generous,Generous
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,7518,Generous,Generous
81,16.66,3.40,Male,No,Thur,Lunch,2,8.33,William Martin,4550549048402707,Thur8232,8232,Generous,Generous
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890,Sun2971,2971,Generous,Generous
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4427601595688633,Sat4056,4056,Generous,Generous

In [67]:
#nlargest,nsmallest
df.nlargest(10,'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,1954,Generous,Generous
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,4590,Generous,Generous
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,t239,Generous,Generous
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,8139,Generous,Generous
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,1025,Generous,Generous
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059,6059,Generous,Generous
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,3374,Generous,Generous
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,9677,Generous,Generous
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2657,Generous,Generous
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003,9003,Generous,Generous

In [68]:
df.nsmallest(10,'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last Four,tip_quality,tip_quality2
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,3455,Generous,Generous
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,3780,Generous,Generous
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,4801,Generous,Generous
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,5032,Generous,Generous
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,2959,Generous,Generous
215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4726904879471,Sat6983,6983,Generous,Generous
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929,2929,Generous,Generous
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,213142079731108,Sat5056,5056,Generous,Generous
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4320272020376174,Thur6600,6600,Generous,Generous
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615,4615,Generous,Generous

In [3]:
df=pd.read_csv('movie_scores.csv')

In [4]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [77]:
# NAN,NA,NAT
np.nan

nan

In [74]:
pd.NaN

AttributeError: module 'pandas' has no attribute 'NaN'

In [75]:
pd.NA

In [76]:
pd.NaT

NaT

In [78]:
#isnull(),notnull()
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [79]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [82]:
df[df['first_name'].notnull()]#df[true /false]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [84]:
df['first_name'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: first_name, dtype: bool

In [85]:
df['first_name' and 'pre_movie_score'].notnull()

0     True
1    False
2    False
3     True
4     True
Name: pre_movie_score, dtype: bool

In [86]:
df[df['pre_movie_score'].isnull() & df['sex'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [6]:
#dropna
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [8]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", None, "Dan"],
    "Age": [25, np.nan, 30, 40],
    "Score": [85, 90, np.nan, 88]
})
df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2   None  30.0    NaN
3    Dan  40.0   88.0

In [18]:
# idxmin ,idxmin,min,max,mean,describe,iloc,loc # already done
df['Age'].idxmin()

0

In [17]:
df['Age'].min()

25.0

In [16]:
df['Score'].max()

90.0

In [24]:
df['Score'].idxmin()# idxmax

0

In [20]:
df['Age'].sum()

np.float64(95.0)

In [21]:
df['Age'].mean()

np.float64(31.666666666666668)

In [25]:
df['Age']*2

0    50.0
1     NaN
2    60.0
3    80.0
Name: Age, dtype: float64

In [26]:
df.sort_values('Age')

    Name   Age  Score
0  Alice  25.0   85.0
2   None  30.0    NaN
3    Dan  40.0   88.0
1    Bob   NaN   90.0

In [28]:
df.sort_values(['Age','Score'])

    Name   Age  Score
0  Alice  25.0   85.0
2   None  30.0    NaN
3    Dan  40.0   88.0
1    Bob   NaN   90.0

In [29]:
df.sort_index()

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2   None  30.0    NaN
3    Dan  40.0   88.0

In [5]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [2, 4, 6, 8, 10],
    'C': [5, 4, 3, 2, 1]
})
df

   A   B  C
0  1   2  5
1  2   4  4
2  3   6  3
3  4   8  2
4  5  10  1

In [34]:
df[['A','B']].corr()

     A    B
A  1.0  1.0
B  1.0  1.0

In [7]:
df['A'].value_counts()

A
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

In [8]:
data = pd.Series(['apple', 'banana', 'apple', 'orange', 'banana', 'apple'])
print(data.value_counts())

apple     3
banana    2
orange    1
Name: count, dtype: int64

In [10]:
df = pd.DataFrame({'A': [1, 2, 3, 2, 1]})
df['A'] = df['A'].replace({1:100, 3:300})
print(df)

     A
0  100
1    2
2  300
3    2
4  100

In [8]:
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [10]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [7]:
df.dropna(thresh=4,axis=1)

  first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

# Fill Data

In [12]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [13]:
df.fillna("NEW Value!") # fill string ,integer etc.

,first_name,last_name,age,sex,pre_movie_score,post_movie_score
0,Tom,Hanks,63.0,m,8.0,10.0
1,NEW Value!,NEW Value!,NEW Value!,NEW Value!,NEW Value!,NEW Value!
2,Hugh,Jackman,51.0,m,NEW Value!,NEW Value!
3,Oprah,Winfrey,66.0,f,6.0,8.0
4,Emma,Stone,31.0,f,7.0,9.0

In [14]:
df['first_name'].fillna("Empty")

0      Tom
1    Empty
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

In [15]:
df['first_name']=df['first_name'].fillna("Empty")

In [16]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1      Empty       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [18]:
df['pre_movie_score'].mean()

np.float64(7.0)

In [20]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

# Filling with Interpolation

In [ ]:
# Be carefull with technique ,you should try to really understand wheather or not tis is valid choice for your data .

In [22]:
airline_tix={'first':100,'bussiness':np.nan,'economy-plus':50,'economy':30}

In [23]:
ser=pd.Series(airline_tix)

In [24]:
ser

first           100.0
bussiness         NaN
economy-plus     50.0
economy          30.0
dtype: float64

In [25]:
ser.interpolate()

first           100.0
bussiness        75.0
economy-plus     50.0
economy          30.0
dtype: float64

In [26]:
ser.interpolate(method='spline')

ValueError: Index column must be numeric or datetime type when using spline method other than linear. Try setting a numeric or datetime index column before interpolating.

In [35]:
df=pd.DataFrame(ser,columns=['Price'])

In [28]:
df

              Price
first         100.0
bussiness       NaN
economy-plus   50.0
economy        30.0

In [29]:
df.interpolate()

              Price
first         100.0
bussiness      75.0
economy-plus   50.0
economy        30.0

In [31]:
df.interpolate(method='spline',order=2)

ValueError: Index column must be numeric or datetime type when using spline method other than linear. Try setting a numeric or datetime index column before interpolating.

# Groupby Operations and Multi_level Index

# Data

In [21]:
df=pd.read_csv('mpg.csv')

In [22]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [23]:
# Create a goupby object waiting for an aggregate method.
df.groupby('model_year')

In [24]:
# model_year becomes the index! It is Not a column name ,it is now the name of the index
df.groupby('model_year')['mpg'].mean()

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [40]:
df.groupby('model_year')[['mpg','cylinders']].mean()

                  mpg  cylinders
model_year
70          17.689655   6.758621
71          21.250000   5.571429
72          18.714286   5.821429
73          17.100000   6.375000
74          22.703704   5.259259
75          20.266667   5.600000
76          21.573529   5.647059
77          23.375000   5.464286
78          24.061111   5.361111
79          25.093103   5.827586
80          33.696552   4.137931
81          30.334483   4.620690
82          31.709677   4.193548

In [41]:
#year=df.groupby('model_year').mean() # avg_year =gropby('model_year').mean(numeric_only=True)

TypeError: agg function failed [how->mean,dtype->object]

In [48]:
avg_year =df.groupby('model_year').mean(numeric_only=True)

In [50]:
avg_year.index

Index([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], dtype='int64', name='model_year')

In [52]:
avg_year.columns

Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration', 'origin'], dtype='object')

In [53]:
avg_year['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [26]:
df.groupby('model_year').mean(numeric_only=True)['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [56]:
df.groupby('model_year').describe()

             mpg                                                          \
           count       mean       std   min     25%    50%     75%   max
model_year
70          29.0  17.689655  5.339231   9.0  14.000  16.00  22.000  27.0
71          28.0  21.250000  6.591942  12.0  15.500  19.00  27.000  35.0
72          28.0  18.714286  5.435529  11.0  13.750  18.50  23.000  28.0
73          40.0  17.100000  4.700245  11.0  13.000  16.00  20.000  29.0
74          27.0  22.703704  6.420010  13.0  16.000  24.00  27.000  32.0
75          30.0  20.266667  4.940566  13.0  16.000  19.50  23.000  33.0
76          34.0  21.573529  5.889297  13.0  16.750  21.00  26.375  33.0
77          28.0  23.375000  6.675862  15.0  17.375  21.75  30.000  36.0
78          36.0  24.061111  6.898044  16.2  19.350  20.70  28.000  43.1
79          29.0  25.093103  6.794217  15.5  19.200  23.90  31.800  37.3
80          29.0  33.696552  7.037983  19.1  29.800  32.70  38.100  46.6
81          29.0  30.334483  5.591465  17.6  26.600  31.60  34.400  39.1
82          31.0  31.709677  5.392548  22.0  27.000  32.00  36.000  44.0

           cylinders            ... acceleration       origin            \
               count      mean  ...          75%   max  count      mean
model_year                      ...
70              29.0  6.758621  ...       15.000  20.5   29.0  1.310345
71              28.0  5.571429  ...       16.125  20.5   28.0  1.428571
72              28.0  5.821429  ...       16.625  23.5   28.0  1.535714
73              40.0  6.375000  ...       16.000  21.0   40.0  1.375000
74              27.0  5.259259  ...       17.000  21.0   27.0  1.666667
75              30.0  5.600000  ...       17.375  21.0   30.0  1.466667
76              34.0  5.647059  ...       17.550  22.2   34.0  1.470588
77              28.0  5.464286  ...       16.925  19.0   28.0  1.571429
78              36.0  5.361111  ...       16.825  21.5   36.0  1.611111
79              29.0  5.827586  ...       17.300  24.8   29.0  1.275862
80              29.0  4.137931  ...       18.700  23.7   29.0  2.206897
81              29.0  4.620690  ...       17.300  20.7   29.0  1.965517
82              31.0  4.193548  ...       18.000  24.6   31.0  1.645161


                 std  min  25%  50%  75%  max
model_year
70          0.603765  1.0  1.0  1.0  1.0  3.0
71          0.741798  1.0  1.0  1.0  2.0  3.0
72          0.792658  1.0  1.0  1.0  2.0  3.0
73          0.667467  1.0  1.0  1.0  2.0  3.0
74          0.832050  1.0  1.0  1.0  2.0  3.0
75          0.730297  1.0  1.0  1.0  2.0  3.0
76          0.706476  1.0  1.0  1.0  2.0  3.0
77          0.835711  1.0  1.0  1.0  2.0  3.0
78          0.837608  1.0  1.0  1.0  2.0  3.0
79          0.591400  1.0  1.0  1.0  1.0  3.0
80          0.818505  1.0  2.0  2.0  3.0  3.0
81          0.944259  1.0  1.0  2.0  3.0  3.0
82          0.914636  1.0  1.0  1.0  3.0  3.0

[13 rows x 48 columns]

In [58]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

# Groupby Multiple Columns

In [60]:
# Lets explore average mpg per year per cylinder count

In [28]:
df.groupby(['model_year','cylinders']).mean(numeric_only=True)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [64]:
df.groupby(['model_year','cylinders']).mean(numeric_only=True).index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

# MultiIndex

In [75]:
# the MultiIndex Ob
year_cyl=df.groupby(['model_year','cylinders']).mean(numeric_only=True)

In [76]:
year_cyl

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [79]:
year_cyl.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [77]:
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [78]:
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

# Grab Based on outside Index

In [80]:
year_cyl.loc[70]

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [81]:
year_cyl.loc[[70,72]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000

# Grab a single Row

In [84]:
year_cyl.loc[(70,8)]

mpg               14.111111
displacement     367.555556
weight          3940.055556
acceleration      11.194444
origin             1.000000
Name: (70, 8), dtype: float64

# Grab with xs

In [85]:
year_cyl.xs(key=70,axis=0,level='model_year')

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [88]:
# Mean coloumn values for 4 cylinders per year
year_cyl.xs(key=4,axis=0,level='cylinders')

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [90]:
# Careful note!
# Keep in mind ,its usually much easier to filter out values before 
df[df['cylinders'].isin([6,8])].groupby(['model_year','cylinders']).mean(numeric_only=True)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         8          13.615385    344.846154  4228.384615     13.000000
73         6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         6          25.900000    196.500000  3145.500000     15.050000
81         6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         6          1.000000
           8          1.000000
71         6          1.000000
           8          1.000000
72         8          1.000000
73         6          1.250000
           8          1.000000
74         6          1.000000
           8          1.000000
75         6          1.000000
           8          1.000000
76         6          1.300000
           8          1.000000
77         6          1.400000
           8          1.000000
78         6          1.166667
           8          1.000000
79         6          1.000000
           8          1.000000
80         6          2.000000
81         6          1.714286
           8          1.000000
82         6          1.000000

# Swap level

In [91]:
year_cyl.swaplevel().head()

,,mpg,displacement,weight,acceleration,origin
cylinders,model_year,,,,,
4,70,25.285714,107.000000,2292.571429,16.000000,2.285714
6,70,20.500000,199.000000,2710.500000,15.500000,1.000000
8,70,14.111111,367.555556,3940.055556,11.194444,1.000000
4,71,27.461538,101.846154,2056.384615,16.961538,1.923077
6,71,18.000000,243.375000,3171.875000,14.750000,1.000000

# Sorting Multiindex

In [93]:
year_cyl.sort_index(level='model_year',ascending=False)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
82         6          28.333333    225.000000  2931.666667     16.033333
           4          32.071429    118.571429  2402.321429     16.703571
81         8          26.600000    350.000000  3725.000000     19.000000
           6          23.428571    184.000000  3093.571429     15.442857
           4          32.814286    108.857143  2275.476190     16.466667
80         6          25.900000    196.500000  3145.500000     15.050000
           5          36.400000    121.000000  2950.000000     19.900000
           4          34.612000    111.000000  2360.080000     17.144000
           3          23.700000     70.000000  2420.000000     12.500000
79         8          18.630000    321.400000  3862.900000     15.400000
           6          22.950000    205.666667  3025.833333     15.433333
           5          25.400000    183.000000  3530.000000     20.100000
           4          31.525000    113.583333  2357.583333     15.991667
78         8          19.050000    300.833333  3563.333333     13.266667
           6          19.066667    213.250000  3314.166667     16.391667
           5          20.300000    131.000000  2830.000000     15.900000
           4          29.576471    112.117647  2296.764706     16.282353
77         8          16.000000    335.750000  4177.500000     13.662500
           6          19.500000    220.400000  3383.000000     16.900000
           4          29.107143    106.500000  2205.071429     16.064286
           3          21.500000     80.000000  2720.000000     13.500000
76         8          14.666667    324.000000  4064.666667     13.222222
           6          20.000000    221.400000  3349.600000     17.000000
           4          26.766667    106.333333  2306.600000     16.866667
75         8          15.666667    330.500000  4108.833333     13.166667
           6          17.583333    233.750000  3398.333333     17.708333
           4          25.250000    114.833333  2489.250000     15.833333
74         8          14.200000    315.200000  4438.400000     14.700000
           6          17.857143    230.428571  3320.000000     16.857143
           4          27.800000     96.533333  2151.466667     16.400000
73         8          13.200000    365.250000  4279.050000     12.250000
           6          19.000000    212.250000  2917.125000     15.687500
           4          22.727273    109.272727  2338.090909     17.136364
           3          18.000000     70.000000  2124.000000     13.500000
72         8          13.615385    344.846154  4228.384615     13.000000
           4          23.428571    111.535714  2382.642857     17.214286
           3          19.000000     70.000000  2330.000000     13.500000
71         8          13.428571    371.714286  4537.714286     12.214286
           6          18.000000    243.375000  3171.875000     14.750000
           4          27.461538    101.846154  2056.384615     16.961538
70         8          14.111111    367.555556  3940.055556     11.194444
           6          20.500000    199.000000  2710.500000     15.500000
           4          25.285714    107.000000  2292.571429     16.000000

                        origin
model_year cylinders
82         6          1.000000
           4          1.714286
81         8          1.000000
           6          1.714286
           4          2.095238
80         6          2.000000
           5          2.000000
           4          2.200000
           3          3.000000
79         8          1.000000
           6          1.000000
           5          2.000000
           4          1.583333
78         8          1.000000
           6          1.166667
           5          2.000000
           4          2.117647
77         8          1.000000
           6          1.400000
           4          1.857143
           3          3.000000
76         8          1.000000
           6          1.300000
           4          1.866667
75         8          1.000000
           6          1.000000
           4          2.166667
74         8          1.000000
           6          1.000000
           4          2.200000
73         8          1.000000
           6          1.250000
           4          2.000000
           3          3.000000
72         8          1.000000
           4          1.928571
           3          3.000000
71         8          1.000000
           6          1.000000
           4          1.923077
70         8          1.000000
           6          1.000000
           4          2.285714

In [94]:
year_cyl.sort_index(level='cylinders',ascending=False)

,,mpg,displacement,weight,acceleration,origin
model_year,cylinders,,,,,
81,8,26.600000,350.000000,3725.000000,19.000000,1.000000
79,8,18.630000,321.400000,3862.900000,15.400000,1.000000
78,8,19.050000,300.833333,3563.333333,13.266667,1.000000
77,8,16.000000,335.750000,4177.500000,13.662500,1.000000
76,8,14.666667,324.000000,4064.666667,13.222222,1.000000
75,8,15.666667,330.500000,4108.833333,13.166667,1.000000
74,8,14.200000,315.200000,4438.400000,14.700000,1.000000
73,8,13.200000,365.250000,4279.050000,12.250000,1.000000
72,8,13.615385,344.846154,4228.384615,13.000000,1.000000
71,8,13.428571,371.714286,4537.714286,12.214286,1.000000
70,8,14.111111,367.555556,3940.055556,11.194444,1.000000
82,6,28.333333,225.000000,2931.666667,16.033333,1.000000
81,6,23.428571,184.000000,3093.571429,15.442857,1.714286
80,6,25.900000,196.500000,3145.500000,15.050000,2.000000
79,6,22.950000,205.666667,3025.833333,15.433333,1.000000
78,6,19.066667,213.250000,3314.166667,16.391667,1.166667
77,6,19.500000,220.400000,3383.000000,16.900000,1.400000
76,6,20.000000,221.400000,3349.600000,17.000000,1.300000
75,6,17.583333,233.750000,3398.333333,17.708333,1.000000
74,6,17.857143,230.428571,3320.000000,16.857143,1.000000
73,6,19.000000,212.250000,2917.125000,15.687500,1.250000
71,6,18.000000,243.375000,3171.875000,14.750000,1.000000
70,6,20.500000,199.000000,2710.500000,15.500000,1.000000
80,5,36.400000,121.000000,2950.000000,19.900000,2.000000
79,5,25.400000,183.000000,3530.000000,20.100000,2.000000
78,5,20.300000,131.000000,2830.000000,15.900000,2.000000
82,4,32.071429,118.571429,2402.321429,16.703571,1.714286
81,4,32.814286,108.857143,2275.476190,16.466667,2.095238
80,4,34.612000,111.000000,2360.080000,17.144000,2.200000
79,4,31.525000,113.583333,2357.583333,15.991667,1.583333
78,4,29.576471,112.117647,2296.764706,16.282353,2.117647
77,4,29.107143,106.500000,2205.071429,16.064286,1.857143
76,4,26.766667,106.333333,2306.600000,16.866667,1.866667
75,4,25.250000,114.833333,2489.250000,15.833333,2.166667
74,4,27.800000,96.533333,2151.466667,16.400000,2.200000
73,4,22.727273,109.272727,2338.090909,17.136364,2.000000
72,4,23.428571,111.535714,2382.642857,17.214286,1.928571
71,4,27.461538,101.846154,2056.384615,16.961538,1.923077
70,4,25.285714,107.000000,2292.571429,16.000000,2.285714
80,3,23.700000,70.000000,2420.000000,12.500000,3.000000
77,3,21.500000,80.000000,2720.000000,13.500000,3.000000
73,3,18.000000,70.000000,2124.000000,13.500000,3.000000
72,3,19.000000,70.000000,2330.000000,13.500000,3.000000

# agg() on a Dataframe

In [97]:
# These strings need to match up with built-in method names
df.agg(['median','mean']) # not run in this version

TypeError: Cannot convert ['130' '165' '150' '150' '140' '198' '220' '215' '225' '190' '170' '160'
 '150' '225' '95' '95' '97' '85' '88' '46' '87' '90' '95' '113' '90' '215'
 '200' '210' '193' '88' '90' '95' '?' '100' '105' '100' '88' '100' '165'
 '175' '153' '150' '180' '170' '175' '110' '72' '100' '88' '86' '90' '70'
 '76' '65' '69' '60' '70' '95' '80' '54' '90' '86' '165' '175' '150' '153'
 '150' '208' '155' '160' '190' '97' '150' '130' '140' '150' '112' '76'
 '87' '69' '86' '92' '97' '80' '88' '175' '150' '145' '137' '150' '198'
 '150' '158' '150' '215' '225' '175' '105' '100' '100' '88' '95' '46'
 '150' '167' '170' '180' '100' '88' '72' '94' '90' '85' '107' '90' '145'
 '230' '49' '75' '91' '112' '150' '110' '122' '180' '95' '?' '100' '100'
 '67' '80' '65' '75' '100' '110' '105' '140' '150' '150' '140' '150' '83'
 '67' '78' '52' '61' '75' '75' '75' '97' '93' '67' '95' '105' '72' '72'
 '170' '145' '150' '148' '110' '105' '110' '95' '110' '110' '129' '75'
 '83' '100' '78' '96' '71' '97' '97' '70' '90' '95' '88' '98' '115' '53'
 '86' '81' '92' '79' '83' '140' '150' '120' '152' '100' '105' '81' '90'
 '52' '60' '70' '53' '100' '78' '110' '95' '71' '70' '75' '72' '102' '150'
 '88' '108' '120' '180' '145' '130' '150' '68' '80' '58' '96' '70' '145'
 '110' '145' '130' '110' '105' '100' '98' '180' '170' '190' '149' '78'
 '88' '75' '89' '63' '83' '67' '78' '97' '110' '110' '48' '66' '52' '70'
 '60' '110' '140' '139' '105' '95' '85' '88' '100' '90' '105' '85' '110'
 '120' '145' '165' '139' '140' '68' '95' '97' '75' '95' '105' '85' '97'
 '103' '125' '115' '133' '71' '68' '115' '85' '88' '90' '110' '130' '129'
 '138' '135' '155' '142' '125' '150' '71' '65' '80' '80' '77' '125' '71'
 '90' '70' '70' '65' '69' '90' '115' '115' '90' '76' '60' '70' '65' '90'
 '88' '90' '90' '78' '90' '75' '92' '75' '65' '105' '65' '48' '48' '67'
 '67' '67' '?' '67' '62' '132' '100' '88' '?' '72' '84' '84' '92' '110'
 '84' '58' '64' '60' '67' '65' '62' '68' '63' '65' '65' '74' '?' '75' '75'
 '100' '74' '80' '76' '116' '120' '110' '105' '88' '85' '88' '88' '88'
 '85' '84' '90' '92' '?' '74' '68' '68' '63' '70' '88' '75' '70' '67' '67'
 '67' '110' '85' '92' '112' '96' '84' '90' '86' '52' '84' '79' '82'] to numeric

In [ ]:
#df.agg(['sum','mean'])[['mpg','weight']]

In [96]:
df[['mpg','weight']].agg(['sum','mean'])

              mpg        weight
sum   9358.800000  1.182229e+06
mean    23.514573  2.970425e+03

# Specify aggregate methods per column

In [98]:
# agg() is very powerfull allowing you to pass in a dictionary where the keys are the columns and the value are a list a aggregate methods.

In [100]:
df.agg({'mpg':['median','mean'],'weight':['mean','std']})

              mpg       weight
median  23.000000          NaN
mean    23.514573  2970.424623
std           NaN   846.841774

In [101]:
# agg() with groupby
df.groupby('model_year').agg({'mpg':['median','mean'],'weight':['mean','std']})

              mpg                  weight
           median       mean         mean          std
model_year
70          16.00  17.689655  3372.793103   852.868663
71          19.00  21.250000  2995.428571  1061.830859
72          18.50  18.714286  3237.714286   974.520960
73          16.00  17.100000  3419.025000   974.809133
74          24.00  22.703704  2877.925926   949.308571
75          19.50  20.266667  3176.800000   765.179781
76          21.00  21.573529  3078.735294   821.371481
77          21.75  23.375000  2997.357143   912.825902
78          20.70  24.061111  2861.805556   626.023907
79          23.90  25.093103  3055.344828   747.881497
80          32.70  33.696552  2436.655172   432.235491
81          31.60  30.334483  2522.931034   533.600501
82          32.00  31.709677  2453.548387   354.276713

In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12]
})

print(df)

     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

In [9]:
df.dropna()

     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

In [14]:
df.dropna(thresh=3)

     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, 8, 10]
})

print(df)

     A     B
0  1.0   5.0
1  2.0   NaN
2  NaN   NaN
3  4.0   8.0
4  5.0  10.0

In [16]:
df.interpolate(method='polynomial', order=2)

     A     B
0  1.0   5.0
1  2.0   5.5
2  3.0   6.5
3  4.0   8.0
4  5.0  10.0

In [17]:
df.interpolate(axis=1)

     A     B
0  1.0   5.0
1  2.0   2.0
2  NaN   NaN
3  4.0   8.0
4  5.0  10.0

# Text Methods

In [79]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to 'utf-8'.
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __sizeof__(self, /)
 |      Return the size of the string in memory, in bytes.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  capitalize(self, /)
 |      Return a capitalized version of the string.
 |
 |      More specifically, make the first character have upper case and the rest lower
 |      case.
 |
 |  casefold(self, /)
 |      Return a version of the string suitable for caseless comparisons.
 |
 |  center(self, width, fillchar=' ', /)
 |      Return a centered string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  count(self, sub[, start[, end]], /)
 |      Return the number of non-overlapping occurrences of substring sub in string S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice notation.
 |
 |  encode(self, /, encoding='utf-8', errors='strict')
 |      Encode the string using the codec registered for encoding.
 |
 |      encoding
 |        The encoding in which to encode the string.
 |      errors
 |        The error handling scheme to use for encoding errors.
 |        The default is 'strict' meaning that encoding errors raise a
 |        UnicodeEncodeError.  Other possible values are 'ignore', 'replace' and
 |        'xmlcharrefreplace' as well as any other name registered with
 |        codecs.register_error that can handle UnicodeEncodeErrors.
 |
 |  endswith(self, suffix[, start[, end]], /)
 |      Return True if the string ends with the specified suffix, False otherwise.
 |
 |      suffix
 |        A string or a tuple of strings to try.
 |      start
 |        Optional start position. Default: start of the string.
 |      end
 |        Optional stop position. Default: end of the string.
 |
 |  expandtabs(self, /, tabsize=8)
 |      Return a copy where all tab characters are expanded using spaces.
 |
 |      If tabsize is not given, a tab size of 8 characters is assumed.
 |
 |  find(self, sub[, start[, end]], /)
 |      Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice notation.
 |      Return -1 on failure.
 |
 |  format(self, /, *args, **kwargs)
 |      Return a formatted version of the string, using substitutions from args and kwargs.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  format_map(self, mapping, /)
 |      Return a formatted version of the string, using substitutions from mapping.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  index(self, sub[, start[, end]], /)
 |      Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice notation.
 |      Raises ValueError when the substring is not found.
 |
 |  isalnum(self, /)
 |      Return True if the string is an alpha-numeric string, False otherwise.
 |
 |      A string is alpha-numeric if all characters in the string are alpha-numeric and
 |      there is at least one character in the string.
 |
 |  isalpha(self, /)
 |      Return True if the string is an alphabetic string, False otherwise.
 |
 |      A string is alphabetic if all characters in the string are alphabetic and there
 |      is at least one character in the string.
 |
 |  isascii(self, /)
 |      Return True if all characters in the string are ASCII, False otherwise.
 |
 |      ASCII characters have code points in the range U+0000-U+007F.
 |      Empty string is ASCII too.
 |
 |  isdecimal(self, /)
 |      Return True if the string is a decimal string, False otherwise.
 |
 |      A string is a decimal string if all characters in the string are decimal and
 |      there is at least one character in the string.
 |
 |  isdigit(self, /)
 |      Return True if the string is a digit string, False otherwise.
 |
 |      A string is a digit string if all characters in the string are digits and there
 |      is at least one character in the string.
 |
 |  isidentifier(self, /)
 |      Return True if the string is a valid Python identifier, False otherwise.
 |
 |      Call keyword.iskeyword(s) to test whether string s is a reserved identifier,
 |      such as "def" or "class".
 |
 |  islower(self, /)
 |      Return True if the string is a lowercase string, False otherwise.
 |
 |      A string is lowercase if all cased characters in the string are lowercase and
 |      there is at least one cased character in the string.
 |
 |  isnumeric(self, /)
 |      Return True if the string is a numeric string, False otherwise.
 |
 |      A string is numeric if all characters in the string are numeric and there is at
 |      least one character in the string.
 |
 |  isprintable(self, /)
 |      Return True if all characters in the string are printable, False otherwise.
 |
 |      A character is printable if repr() may use it in its output.
 |
 |  isspace(self, /)
 |      Return True if the string is a whitespace string, False otherwise.
 |
 |      A string is whitespace if all characters in the string are whitespace and there
 |      is at least one character in the string.
 |
 |  istitle(self, /)
 |      Return True if the string is a title-cased string, False otherwise.
 |
 |      In a title-cased string, upper- and title-case characters may only
 |      follow uncased characters and lowercase characters only cased ones.
 |
 |  isupper(self, /)
 |      Return True if the string is an uppercase string, False otherwise.
 |
 |      A string is uppercase if all cased characters in the string are uppercase and
 |      there is at least one cased character in the string.
 |
 |  join(self, iterable, /)
 |      Concatenate any number of strings.
 |
 |      The string whose method is called is inserted in between each given string.
 |      The result is returned as a new string.
 |
 |      Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'
 |
 |  ljust(self, width, fillchar=' ', /)
 |      Return a left-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  lower(self, /)
 |      Return a copy of the string converted to lowercase.
 |
 |  lstrip(self, chars=None, /)
 |      Return a copy of the string with leading whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  partition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string.  If the separator is found,
 |      returns a 3-tuple containing the part before the separator, the separator
 |      itself, and the part after it.
 |
 |      If the separator is not found, returns a 3-tuple containing the original string
 |      and two empty strings.
 |
 |  removeprefix(self, prefix, /)
 |      Return a str with the given prefix string removed if present.
 |
 |      If the string starts with the prefix string, return string[len(prefix):].
 |      Otherwise, return a copy of the original string.
 |
 |  removesuffix(self, suffix, /)
 |      Return a str with the given suffix string removed if present.
 |
 |      If the string ends with the suffix string and that suffix is not empty,
 |      return string[:-len(suffix)]. Otherwise, return a copy of the original
 |      string.
 |
 |  replace(self, old, new, /, count=-1)
 |      Return a copy with all occurrences of substring old replaced by new.
 |
 |        count
 |          Maximum number of occurrences to replace.
 |          -1 (the default value) means replace all occurrences.
 |
 |      If the optional argument count is given, only the first count occurrences are
 |      replaced.
 |
 |  rfind(self, sub[, start[, end]], /)
 |      Return the highest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice notation.
 |      Return -1 on failure.
 |
 |  rindex(self, sub[, start[, end]], /)
 |      Return the highest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice notation.
 |      Raises ValueError when the substring is not found.
 |
 |  rjust(self, width, fillchar=' ', /)
 |      Return a right-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  rpartition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string, starting at the end. If
 |      the separator is found, returns a 3-tuple containing the part before the
 |      separator, the separator itself, and the part after it.
 |
 |      If the separator is not found, returns a 3-tuple containing two empty strings
 |      and the original string.
 |
 |  rsplit(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any whitespace
 |          character (including \n \r \t \f and spaces) and will discard
 |          empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the end of the string and works to the front.
 |
 |  rstrip(self, chars=None, /)
 |      Return a copy of the string with trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  split(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any whitespace
 |          character (including \n \r \t \f and spaces) and will discard
 |          empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the front of the string and works to the end.
 |
 |      Note, str.split() is mainly useful for data that has been intentionally
 |      delimited.  With natural text that includes punctuation, consider using
 |      the regular expression module.
 |
 |  splitlines(self, /, keepends=False)
 |      Return a list of the lines in the string, breaking at line boundaries.
 |
 |      Line breaks are not included in the resulting list unless keepends is given and
 |      true.
 |
 |  startswith(self, prefix[, start[, end]], /)
 |      Return True if the string starts with the specified prefix, False otherwise.
 |
 |      prefix
 |        A string or a tuple of strings to try.
 |      start
 |        Optional start position. Default: start of the string.
 |      end
 |        Optional stop position. Default: end of the string.
 |
 |  strip(self, chars=None, /)
 |      Return a copy of the string with leading and trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  swapcase(self, /)
 |      Convert uppercase characters to lowercase and lowercase characters to uppercase.
 |
 |  title(self, /)
 |      Return a version of the string where each word is titlecased.
 |
 |      More specifically, words start with uppercased characters and all remaining
 |      cased characters have lower case.
 |
 |  translate(self, table, /)
 |      Replace each character in the string using the given translation table.
 |
 |        table
 |          Translation table, which must be a mapping of Unicode ordinals to
 |          Unicode ordinals, strings, or None.
 |
 |      The table must implement lookup/indexing via __getitem__, for instance a
 |      dictionary or list.  If this operation raises LookupError, the character is
 |      left untouched.  Characters mapped to None are deleted.
 |
 |  upper(self, /)
 |      Return a copy of the string converted to uppercase.
 |
 |  zfill(self, width, /)
 |      Pad a numeric string with zeros on the left, to fill a field of the given width.
 |
 |      The string is never truncated.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  maketrans(x, y=<unrepresentable>, z=<unrepresentable>, /)
 |      Return a translation table usable for str.translate().
 |
 |      If there is only one argument, it must be a dictionary mapping Unicode
 |      ordinals (integers) or characters to Unicode ordinals, strings or None.
 |      Character keys will be then converted to ordinals.
 |      If there are two arguments, they must be strings of equal length, and
 |      in the resulting dictionary, each character in x will be mapped to the
 |      character at the same position in y. If there is a third argument, it
 |      must be a string, whose characters will be mapped to None in the result.

In [4]:
names=pd.Series(['andrew','bobo','chaire','david','4'])
names

0    andrew
1      bobo
2    chaire
3     david
4         4
dtype: object

In [3]:
names.str.capitalize()

0    Andrew
1      Bobo
2    Chaire
3     David
4         4
dtype: object

In [4]:
names.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [5]:
names.str.contains('x')

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [7]:
names.str.replace('a','@')

0    @ndrew
1      bobo
2    ch@ire
3     d@vid
4         4
dtype: object

In [10]:
names.str.split(' ')

0    [andrew]
1      [bobo]
2    [chaire]
3     [david]
4         [4]
dtype: object

# Spiliting ,Grabbing and Expending

In [5]:
tech_finance=['GooG,APPL','JPM,BAC,GS']
len(tech_finance)

2

In [6]:
tickers=pd.Series(tech_finance)
tickers

0     GooG,APPL
1    JPM,BAC,GS
dtype: object

In [7]:
tickers.str.split(",")

0      [GooG, APPL]
1    [JPM, BAC, GS]
dtype: object

In [8]:
tickers.str.split(',').str[0]

0    GooG
1     JPM
dtype: object

In [10]:
tickers.str.split(',',expand=True)

      0     1     2
0  GooG  APPL  None
1   JPM   BAC    GS

# cleaning or Editing String

In [18]:
messy_names=pd.Series(["andrew ","bob;bo"," chaire "])
messy_names

0     andrew
1      bob;bo
2     chaire
dtype: object

In [20]:
messy_names.str.replace(";","")

0     andrew
1       bobbo
2     chaire
dtype: object

In [19]:
messy_names.str.replace(";","").str.strip().str.capitalize()

0    Andrew
1     Bobbo
2    Chaire
dtype: object

# Alternative with custom apply() call

In [23]:
def cleanup(name):
    name=name.replace(";","")
    name=name.strip()
    name=name.capitalize()
    return name
messy_names.apply(cleanup)

0    Andrew
1     Bobbo
2    Chaire
dtype: object

# Python datetime Review

In [24]:
# Basic Python output of pandas contains a datetime libarary

In [25]:
# to illustrate the order of arguments

In [13]:
from datetime import datetime

In [14]:
my_year=2017
my_month=1
my_day=2
my_hour=13
my_minute=30
my_second=15

In [29]:
#january 2nd 2017

In [15]:
my_date=datetime(my_year,my_month,my_day)
#default to 0.00
my_date

datetime.datetime(2017, 1, 2, 0, 0)

In [31]:
# january 2nd ,2017 at 13:30:15
my_date=datetime(my_year,my_month,my_day,my_hour,my_minute,my_second)

In [32]:
my_date

datetime.datetime(2017, 1, 2, 13, 30, 15)

In [33]:
my_date.day

2

In [19]:
my_date.time()

datetime.time(0, 0)

In [17]:
my_date.year

2017

In [20]:
my_date.month

1

In [21]:
df = pd.DataFrame({'year':[2024,2024],'month':[1,2],'day':[10,20]})
df['Date'] = pd.to_datetime(df[['year','month','day']])

In [23]:
df['Date'].dt.year

0    2024
1    2024
Name: Date, dtype: int32

In [24]:
df['Date'].dt.time

0    00:00:00
1    00:00:00
Name: Date, dtype: object

# converting the datetime

In [26]:
myser=(['Nov 3 , 2000','2000-01-01',None])

In [46]:
myser

['Nov 3 , 2000', '2000-01-01', None]

In [47]:
myser[0]

'Nov 3 , 2000'

# converting-to-timestamps

In [53]:
pd.to_datetime(myser,format='mixed')

DatetimeIndex(['2000-11-03', '2000-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)

In [55]:
pd.to_datetime(myser,format='mixed')[0]

Timestamp('2000-11-03 00:00:00')

In [56]:
obvi_euro_date='31-12-2000'

In [57]:
pd.to_datetime(obvi_euro_date,dayfirst=True)

Timestamp('2000-12-31 00:00:00')

In [58]:
euro_date='10-12-2000'
pd.to_datetime(euro_date,dayfirst=True)

Timestamp('2000-12-10 00:00:00')

# Custom time String Formating

In [59]:
# sometimes dates can have a non_standard formate ,you can always specify to pandas the format.

In [66]:
style_date='12-Dec-2000'

In [67]:
pd.to_datetime(style_date,format='mixed')

Timestamp('2000-12-12 00:00:00')

# Data

In [68]:
sales=pd.read_csv('Retailsales_BeerWineLiquor.csv')

In [69]:
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [71]:
sales.iloc[0]['DATE']

'1992-01-01'

In [72]:
type(sales.iloc[0]['DATE'])

str

In [74]:
sales['DATE']=pd.to_datetime(sales['DATE'])

In [75]:
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

# Pivot tables

In [80]:
# pivoting data can somtimes help clarify relationships and connections .

# Data import

In [82]:
df=pd.read_csv('Sales_Funnel_CRM.csv')

In [83]:
df

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
5,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Analytics,300,2800000,Under Review
6,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Prediction,150,700000,Presented
7,1216870,Microsoft,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
8,2200450,Walmart,Will Grates,Edward Thorp,Analytics,150,2450000,Lost
9,405886,Apple,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
10,470248,Exxon Mobile,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
11,698032,ATT,Cindy Phoner,Claude Shannon,Tracking,150,350000,Under Review
12,698032,ATT,Cindy Phoner,Claude Shannon,Prediction,150,700000,Presented
13,902797,CVS Health,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
14,2046943,Salesforce,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
15,2169499,Cisco,Emma Gordian,Claude Shannon,Analytics,300,4550000,Lost
16,2169499,Cisco,Emma Gordian,Claude Shannon,GPS Positioning,300,350000,Presented

# The Pivot Method()

In [84]:
# Lets take a subset otherwise we will get an error due to duplicate row and data .

In [85]:
licenses=df[['Company','Product','Licenses']]

In [86]:
licenses

         Company          Product  Licenses
0         Google        Analytics       150
1         Google       Prediction       150
2         Google         Tracking       300
3           BOBO        Analytics       150
4           IKEA        Analytics       300
5     Tesla Inc.        Analytics       300
6     Tesla Inc.       Prediction       150
7      Microsoft         Tracking       300
8        Walmart        Analytics       150
9          Apple        Analytics       300
10  Exxon Mobile        Analytics       150
11           ATT         Tracking       150
12           ATT       Prediction       150
13    CVS Health         Tracking       450
14    Salesforce        Analytics       750
15         Cisco        Analytics       300
16         Cisco  GPS Positioning       300

In [88]:
pd.pivot(data=licenses,index='Company',columns='Product',values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

# The pivot_table method

In [89]:
pd.pivot_table(df,index='Company',aggfunc=('sum'))

,Account Manager,Account Number,Contact,Licenses,Product,Sale Price,Status
Company,,,,,,,
Google,Edward ThorpEdward ThorpEdward Thorp,6370194,Larry PagerLarry PagerLarry Pager,600,AnalyticsPredictionTracking,3150000,PresentedPresentedUnder Review
ATT,Claude ShannonClaude Shannon,1396064,Cindy PhonerCindy Phoner,300,TrackingPrediction,1050000,Under ReviewPresented
Apple,Claude Shannon,405886,Cindy Phoner,300,Analytics,4550000,Won
BOBO,Edward Thorp,2192650,Larry Pager,150,Analytics,2450000,Lost
CVS Health,Claude Shannon,902797,Emma Gordian,450,Tracking,490000,Won
Cisco,Claude ShannonClaude Shannon,4338998,Emma GordianEmma Gordian,600,AnalyticsGPS Positioning,4900000,LostPresented
Exxon Mobile,Claude Shannon,470248,Cindy Phoner,150,Analytics,2100000,Presented
IKEA,Edward Thorp,420496,Elon Tusk,300,Analytics,4550000,Won
Microsoft,Edward Thorp,1216870,Will Grates,300,Tracking,350000,Under Review
Salesforce,Claude Shannon,2046943,Emma Gordian,750,Analytics,7000000,Won
Tesla Inc.,Edward ThorpEdward Thorp,1273370,Elon TuskElon Tusk,450,AnalyticsPrediction,3500000,Under ReviewPresented
Walmart,Edward Thorp,2200450,Will Grates,150,Analytics,2450000,Lost

# Either grab the columns

In [90]:
pd.pivot_table(df,index='Company',aggfunc=('sum'))[['Licenses','Sale Price']]

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [91]:
# or state them as wanted value

In [93]:
pd.pivot_table(df,index='Company',aggfunc='sum',values=['Licenses','Sale Price'])

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [94]:
# or group by

In [95]:
df.groupby('Company').sum()[['Licenses','Sale Price']]

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [2]:
import pandas as pd
df = pd.DataFrame({
    'City': ['Delhi', 'Delhi', 'Mumbai', 'Mumbai', 'Chennai'],
    'Month': ['Jan','Feb','Jan','Feb','Jan'],
    'Sales':[100,120,90,110,95]
})
pivot_tbl = pd.pivot_table(df, values='Sales', index='City', columns='Month', aggfunc='mean', fill_value=0)

In [4]:
pivot_tbl

Month      Feb    Jan
City
Chennai    0.0   95.0
Delhi    120.0  100.0
Mumbai   110.0   90.0

In [12]:
pd.pivot_table(df,index='City',aggfunc=('sum'))['Month']

City
Chennai       Jan
Delhi      JanFeb
Mumbai     JanFeb
Name: Month, dtype: object

In [11]:
pd.pivot_table(df,index='City',aggfunc='sum',values=['Month'])

          Month
City
Chennai     Jan
Delhi    JanFeb
Mumbai   JanFeb

In [14]:
df.groupby('City').sum()['Month']

City
Chennai       Jan
Delhi      JanFeb
Mumbai     JanFeb
Name: Month, dtype: object

In [2]:
# self work
import pandas as pd 
df=pd.DataFrame({'A':[1,1,2,2],'B':[10,20,30,40]})
print(df.groupby('A')['B'].mean())

A
1    15.0
2    35.0
Name: B, dtype: float64

In [16]:
array=[['2024','2024','2024','2025','2025'],['jan','Feb','Mar','Jan','Feb']]
index=pd.MultiIndex.from_arrays(array,names=('year','Month'))
df=pd.DataFrame({'Sales':[100,150,120,130,170]},index=index)
df

            Sales
year Month
2024 jan      100
     Feb      150
     Mar      120
2025 Jan      130
     Feb      170

In [17]:
mask=df[(df.index.get_level_values('year')=='2025')&(df.index.get_level_values('Month').isin(['Jan','Feb']))]

In [18]:
mask

            Sales
year Month
2025 Jan      130
     Feb      170

In [19]:
df=pd.DataFrame({'team':['A','A','B','B','C'],'player':['x','y','z','w','p'],'score':[10,20,15,25,30]})
df

  team player  score
0    A      x     10
1    A      y     20
2    B      z     15
3    B      w     25
4    C      p     30

In [35]:
idx=df.groupby('team')['score'].idxmax()
idx

team
A    1
B    3
C    4
Name: score, dtype: int64

In [32]:
highest_score=df.loc[idx]

In [33]:
highest_score

  team player  score
1    A      y     20
3    B      w     25
4    C      p     30